import streamlit as st
import json
import os
import subprocess
import sys

# -----------------------------
# Page Config
# -----------------------------
st.set_page_config(
    page_title="AI Interview Coach",
    page_icon="🎤",
    layout="wide"
)
if st.button("🔄 Refresh Results"):
    st.rerun()
# -----------------------------
# Load Results
# -----------------------------
if os.path.exists("results.json"):
    with open("results.json", "r") as file:
        results = json.load(file)
else:
    results = {
        "eye_contact": 0,
        "attention_score": 0,
        "communication_score": 0,
        "overall_score": 0,
        "filler_words": 0,
        "duration": "00:00"
    }

# -----------------------------
# Header
# -----------------------------
st.title("🎤 AI Interview Coach")
st.markdown("""
### 🚀 Features
- 👀 Real-time Eye Contact Tracking
- 🧠 Head Pose & Attention Analysis
- 🎤 Speech Transcription using Faster-Whisper
- 🗣️ Filler Word Detection
- 📊 Performance Dashboard
- 📥 Downloadable Interview Report
""")

st.caption(
    "AI-powered interview preparation platform using "
    "Computer Vision and Speech Intelligence."
)

st.write(
    "Practice interviews and receive AI-powered feedback on:"
)

st.write(
    "✅ Eye Contact    "
    "✅ Attention    "
    "✅ Communication    "
    "✅ Filler Words"
)

# -----------------------------
# Start Interview Button
# -----------------------------

if st.button("🎥 Start New Interview"):
    subprocess.Popen(
        [sys.executable, "main.py"]
    )
    st.success("Interview started! Webcam opening...")

st.divider()

# -----------------------------
# Metrics
# -----------------------------
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        "👀 Eye Contact",
        f"{results['eye_contact']}%"
    )

with col2:
    st.metric(
        "🧠 Attention",
        f"{results['attention_score']}%"
    )

with col3:
    st.metric(
        "🎤 Communication",
        f"{results['communication_score']}%"
    )

with col4:
    st.metric(
        "⭐ Overall",
        f"{results['overall_score']}%"
    )

# -----------------------------
# Extra Info
# -----------------------------
st.divider()

col5, col6 = st.columns(2)

with col5:
    st.info(
        f"⏱ Interview Duration: "
        f"{results['duration']}"
    )

with col6:
    st.info(
        f"🗣️ Filler Words Used: "
        f"{results['filler_words']}"
    )

# -----------------------------
# Performance Breakdown
# -----------------------------
st.subheader("📊 Performance Breakdown")

st.write(
    f"👀 Eye Contact ({results['eye_contact']}%)"
)
st.progress(results["eye_contact"] / 100)

st.write(
    f"🧠 Attention ({results['attention_score']}%)"
)
st.progress(results["attention_score"] / 100)

st.write(
    f"🎤 Communication ({results['communication_score']}%)"
)
st.progress(results["communication_score"] / 100)

st.write(
    f"⭐ Overall ({results['overall_score']}%)"
)
st.progress(results["overall_score"] / 100)

# -----------------------------
# Feedback
# -----------------------------
st.subheader("💬 Feedback")

if results["eye_contact"] >= 80:
    st.success("Excellent eye contact maintained.")
elif results["eye_contact"] >= 60:
    st.warning("Good eye contact, but could be improved.")
else:
    st.error("Try maintaining eye contact with the camera.")

if results["communication_score"] >= 80:
    st.success("Strong communication skills.")
else:
    st.warning("Speak more clearly and confidently.")

if results["filler_words"] == 0:
    st.success("No filler words detected.")
elif results["filler_words"] <= 3:
    st.warning("A few filler words detected.")
else:
    st.error(
        f"High filler word usage ({results['filler_words']})."
    )

# -----------------------------
# Download Report
# -----------------------------
report = f"""
AI INTERVIEW REPORT
========================

Duration: {results['duration']}
Eye Contact: {results['eye_contact']}%
Attention Score: {results['attention_score']}%
Communication Score: {results['communication_score']}%
Overall Score: {results['overall_score']}%
Filler Words: {results['filler_words']}

Feedback:
- Maintain eye contact with the camera.
- Speak confidently and clearly.
- Minimize filler words.

Generated by AI Interview Coach
"""

st.download_button(
    label="📥 Download Report",
    data=report,
    file_name="interview_report.txt",
    mime="text/plain"
)